FROM php:8.3-apache

ENV TZ=America/Fortaleza

# Copia vhost do Apache e script de inicialização
COPY config/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY init.sh /init.sh

RUN apt-get update && apt-get install -y --no-install-recommends \
        libzip-dev \
        libpng-dev \
        libicu-dev \
        libldap2-dev \
        libbz2-dev \
    && ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so \
    && ln -s /usr/lib/x86_64-linux-gnu/liblber.so /usr/lib/liblber.so \
    && docker-php-ext-install \
        mysqli \
        pdo \
        pdo_mysql \
        exif \
        gd \
        intl \
        ldap \
        opcache \
        zip \
        bz2 \
    && a2enmod rewrite \
    && a2ensite 000-default.conf \
    && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && sed -i 's/^;date.timezone =.*/date.timezone = America\/Fortaleza/' /usr/local/etc/php/php.ini \
    && sed -i 's/^session.cookie_httponly =.*/session.cookie_httponly = On/' /usr/local/etc/php/php.ini \
    && chmod +x /init.sh \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /var/www/html

EXPOSE 80

ENTRYPOINT ["/init.sh"]
